### ISSUE TITLE
Natbib ordenar citas en orden de aparición

### ISSUE THREAD

**Issue by dgarridoa** [Template-Latex/Template-Tesis#2]
Hola, el código por defecto ordena las citas por nombre de autor y quiero ordenarlas por orden de aparición probe usando:

\bibliographystyle{unsrtnat} y \natbibrefstyle {unsrt}, ambas me funcionan en Overleaf, pero no en PDFLaTex, no me arroja ningún error y no alteran el orden de las referencias.

**Comment by ppizarror** [comment]
Hola. Si funciona en overleaf, probaste a eliminar los archivos temporales y luego recompilar?

**Comment by tmsl31** [comment]
Hola,

Creo que tengo el mismo problema. Lo que pasa es que al citar, por ejemplo, mi primera referencia, le asigna el número 9 y después asigna números aleatorios(?) (al menos no veo el patrón)

Tengo mis referencias en un .bib y agregué las siguientes instrucciones antes de agregar la biblio.

\stylecitereferences{natbib}
\natbibrefstyle{ieeetr}
\natbibnumbers

\bibliography{library.bib}

**Comment by ppizarror** [comment]
> ieeetr

Hola, para eso yo hice la prueba en mi pc y andaba bien. Tienes que cambiar lib/config.tex.

Algunas configuraciones que deberías tener: (ultima versión)
\def\natbibnumbers {true}
\def\natbibrefstyle {ieeetr}
\def\stylecitereferences {natbib}

**Comment by tmsl31** [comment]
Gracias! Con eso anduvo perfecto

**Comment by ppizarror** [comment]
> Gracias! Con eso anduvo perfecto

Quizás es poco intuitivo este tema, pero en sí el template es demasiado complejo por eso para dar soporte a 3 motores distintos de referencias tuve que tomar ciertas decisiones. Si algo no queda muy claro en el manual (todos los templates heredan de template informe) por favor crear un pull request en el manual: https://github.com/Template-Latex/template-latex.github.io

saludos!
