### ISSUE TITLE
Sobre \addimages

### ISSUE THREAD

**Issue by gablairu** [Template-Latex/Template-Tesis#4]
Hola,
Actualmente estoy utilizando el código \addimages y me ha funcionado súper para aunar varias imágenes en un mismo entorno. El problema es que en algunos casos me gustaría separar las imágenes en dos páginas para ahorrar algo de espacio, un símil del \ContinuedFloat que se puede hacer al usar \subfigure ¿Existe esta posibilidad usando \addimages? Les leo

**Comment by ppizarror** [comment]
Hola, es una buena idea, podría implementarlo, pero requeriría de tener un ejemplo corriendo dentro del template. Si encuentras un ejemplo que funcione y me compartes el código lo podía convertir a algun entorno o función para que sea compatible con \addimages (que ya de por sí tiene muchos hacks para que sea fácil de usar...)

**Comment by ppizarror** [comment]
Por fin pude completar este issue. La nueva `v3.2.3` incorpora el método `\imagescontinuenumbering`. Esto fue posible por la adopción del paquete `subcaption,` reemplazando el código asociado al antiguo `subfig`.

Saludos,
