### ISSUE TITLE
Sobre estilo de bibliografía custom y separación de imágenes

### ISSUE THREAD

**Issue by Mp7rough** [Template-Latex/Template-Tesis#5]
Buenas¡ hace poco envíe un correo sobre el estilo iso 690 (mil disculpas), lo solucioné fácil con :
\usepackage[backend=biber, style=iso-authoryear, giveninits=true]{biblatex} 
\addbibresource{library.bib}

El problema es que ahora no me aparece en la tabla de contenidos y al incluir un chapter nuevo para incluirla me queda o duplicado el "bibliografía" , con el título de "capitulo x" y bibliografía pero esta se imprime en otra página , uso \printbibliography para generar la bibliografía

Y lo segundo es sobre una separación de categorías en las imágenes por ejemplo todas mis gráficas son imágenes pero debo incluir unas figuras extras, y al cambiar la etiqueta por gráficas (ya que son la mayoría) y al probar con esto: 

\begin{figure}
	\captionsetup{labelformat=default,labelsep=colon,name=Figura}
	\centering
	\includegraphics[width=\textwidth, resolution=75]{Ventana.png}
	\caption{Ventana de ingreso de datos señalizadas sus partes}
	\label{fig:ventana}
\end{figure}

y me cambia la etiqueta a figura, pero en la tabla de contenidos sigue con la numeración de las gráficas no habiendo distinción.

Muchas gracias por el template¡ realmente queda hermoso todo, saludos.

**Comment by ppizarror** [comment]
Hola. Vi tu correo pero no he tenido mucho tiempo para responder o ver mis proyectos personales.

1. Para la bibliografía ya que estás usando un estilo "custom" debes configurar **\def\stylecitereferences** en {custom}. Y para que aparezca en el índice debes llamarlo asi:
```latex
\chapter{ultimo capitulo}
...

% BIBLIOGRAFIA
\printbibliography[heading=bibintoc]
```

Como mejora, agregué un ejemplo en el manual web (https://latex.ppizarror.com/informe#hlp-ref).

2. Para lograr distintos índices tendrás que generar una "lista" de objetos distinta para separar las figuras. *Out of the box* soporto solamente listas para ecuaciones, figuras, codigos y tablas. Si quieres seguir esa línea, te recomiendo revisar el código del template, y hacer algo similar a mis funciones custom "**equationindex**", el contador "**templateIndexEquations**" y el insertor en bibliografía **\templateIndexEquations**. No es algo que vaya a agregar al template. También deberías modificar la función **\templateIndex** para soportar tu nuevo entorno.

**Comment by ppizarror** [comment]
Hola, cerraré este issue. Si hay algún otro problema o solicitud no dudes en crear uno nuevo. Saludos! c:

**Comment by Mp7rough** [comment]
Genial muchas gracias¡ a la perfección quedó la bibliografía, lo de las imágenes vs gráfica intentare hacerlo 🤕 lo comentaré pronto, muchas gracias!

Tuve un problema al agregar la bibliografía a la tabla de contenidos, porque por alguna razón las tablas de contenido de tablas y figuras desaparecían. lo solucione con esta alternativa :

\clearpage
\phantomsection
\addcontentsline{toc}{chapter}{Bibliografía} 
\printbibliography
